version: '3.9'

services:
  
  #blogzilla:
  #  build:
  #    context: ./
  #    dockerfile: blogzilla.dockerfile
  #  working_dir: /opt/project
  #  volumes:
  #    - .:/opt/project
  #  command: sleep infinity
  #  ports:
  #    - 8080:8080
  #  networks:
  #    - bznetwork

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bznetwork

  prometheus:
      image: prom/prometheus
      volumes:
        - ./prometheus/:/etc/prometheus/
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
      ports:
        - 9090:9090
      networks:
        - bznetwork

  grafana:
      image: grafana/grafana
      ports:
        - 3000:3000
      networks:
        - bznetwork

volumes:
  postgres-data:

networks:
  bznetwork: