postgres:
  host: localhost
  port: 5432
  user: postgres
  password: example
  database: postgres

defaultuser:
  username: admin
  password: admin

login:
  expiry: 20
  secret: thesecret

server:
  port: 8080